-- Controle Queijos — Supabase Cloud V7.51
-- Execute este arquivo no SQL Editor do seu projeto Supabase.
-- O mesmo usuário do Supabase poderá usar vários Androids e enxergar os mesmos dados.

create extension if not exists pgcrypto;

create table if not exists public.cq_clients (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  phone text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cq_products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  quantity integer not null default 0,
  entry_value numeric(12,2) not null default 0,
  exit_value numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cq_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_id bigint,
  customer_name text not null default '',
  product_id bigint,
  product_name text not null default '',
  quantity integer not null default 0,
  unit_value numeric(12,2) not null default 0,
  unit_cost numeric(12,2) not null default 0,
  total_value numeric(12,2) not null default 0,
  paid_value numeric(12,2) not null default 0,
  order_date bigint not null default 0,
  delivery_date bigint not null default 0,
  status text not null default 'Pendente',
  stock_applied boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cq_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint,
  amount numeric(12,2) not null default 0,
  payment_date bigint not null default 0,
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.cq_sales (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint,
  product_name text not null default '',
  quantity integer not null default 0,
  unit_value numeric(12,2) not null default 0,
  unit_cost numeric(12,2) not null default 0,
  sale_date bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.cq_expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  description text not null default '',
  value numeric(12,2) not null default 0,
  expense_date bigint not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists cq_clients_user_idx on public.cq_clients(user_id);
create index if not exists cq_products_user_idx on public.cq_products(user_id);
create index if not exists cq_orders_user_idx on public.cq_orders(user_id);
create index if not exists cq_orders_customer_idx on public.cq_orders(customer_id);
create index if not exists cq_payments_user_idx on public.cq_payments(user_id);
create index if not exists cq_sales_user_idx on public.cq_sales(user_id);
create index if not exists cq_expenses_user_idx on public.cq_expenses(user_id);

alter table public.cq_clients enable row level security;
alter table public.cq_products enable row level security;
alter table public.cq_orders enable row level security;
alter table public.cq_payments enable row level security;
alter table public.cq_sales enable row level security;
alter table public.cq_expenses enable row level security;

drop policy if exists cq_clients_owner on public.cq_clients;
create policy cq_clients_owner on public.cq_clients for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists cq_products_owner on public.cq_products;
create policy cq_products_owner on public.cq_products for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists cq_orders_owner on public.cq_orders;
create policy cq_orders_owner on public.cq_orders for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists cq_payments_owner on public.cq_payments;
create policy cq_payments_owner on public.cq_payments for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists cq_sales_owner on public.cq_sales;
create policy cq_sales_owner on public.cq_sales for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists cq_expenses_owner on public.cq_expenses;
create policy cq_expenses_owner on public.cq_expenses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.cq_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cq_clients_touch on public.cq_clients;
create trigger cq_clients_touch before update on public.cq_clients for each row execute function public.cq_touch_updated_at();

drop trigger if exists cq_products_touch on public.cq_products;
create trigger cq_products_touch before update on public.cq_products for each row execute function public.cq_touch_updated_at();

drop trigger if exists cq_orders_touch on public.cq_orders;
create trigger cq_orders_touch before update on public.cq_orders for each row execute function public.cq_touch_updated_at();


-- Acesso explícito à Data API para usuários autenticados.
-- O RLS continua limitando cada linha ao usuário autenticado.
grant select, insert, update, delete on table
  public.cq_clients, public.cq_products, public.cq_orders,
  public.cq_payments, public.cq_sales, public.cq_expenses
  to authenticated;

-- Necessário para IDs gerados por identity.
grant usage, select on all sequences in schema public to authenticated;

comment on table public.cq_clients is 'Controle Queijos — clientes sincronizados na nuvem';
comment on table public.cq_products is 'Controle Queijos — produtos sincronizados na nuvem';
comment on table public.cq_orders is 'Controle Queijos — encomendas sincronizadas na nuvem';
comment on table public.cq_payments is 'Controle Queijos — recebimentos sincronizados na nuvem';
comment on table public.cq_sales is 'Controle Queijos — vendas sincronizadas na nuvem';
comment on table public.cq_expenses is 'Controle Queijos — gastos sincronizados na nuvem';
